name: Python and Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3.1.4


      - name: Run install_imports.sh
        run: |
          chmod +x install_imports.sh
          ./install_imports.sh

      - name: Set up Docker Compose
        uses: docker/compose-action@v1

      - name: Run run_tests.sh
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
