name: Python and Docker CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Setup Python
      uses: actions/setup-python@v3.1.4
      
    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server mysql-client
      
    - name: Run install_imports.sh
      run: |
          sh install_imports.sh
    

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d 

      
    - name: Wait for services to start
      run: docker network inspect byui_fn_project_cse111_default
      
    - name: Run run_tests.sh
      run: |
          cd src
          python -m unittest discover -s . -p "*.py"

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
  

      


      
      

      
        
